const textronPreSixSigmaData = [
  {
    Month: "Jan (Q1)",
    DefectRate_DPMO: 25000,
    ScrapRework_Cost_M: 1.5,
    OnTimeDelivery_Pct: 92.5,
    ProcessYield_Pct: 97.5,
  },
  {
    Month: "Feb (Q1)",
    DefectRate_DPMO: 28000,
    ScrapRework_Cost_M: 1.6,
    OnTimeDelivery_Pct: 91.0,
    ProcessYield_Pct: 97.2,
  },
  {
    Month: "Mar (Q1)",
    DefectRate_DPMO: 31000,
    ScrapRework_Cost_M: 1.8,
    OnTimeDelivery_Pct: 90.0,
    ProcessYield_Pct: 96.9,
  },
  {
    Month: "Apr (Q2)",
    DefectRate_DPMO: 35000,
    ScrapRework_Cost_M: 2.0,
    OnTimeDelivery_Pct: 88.5,
    ProcessYield_Pct: 96.5,
  },
  {
    Month: "May (Q2)",
    DefectRate_DPMO: 32000,
    ScrapRework_Cost_M: 1.9,
    OnTimeDelivery_Pct: 89.0,
    ProcessYield_Pct: 96.8,
  },
  {
    Month: "Jun (Q2)",
    DefectRate_DPMO: 38000,
    ScrapRework_Cost_M: 2.2,
    OnTimeDelivery_Pct: 86.5,
    ProcessYield_Pct: 96.2,
  },
  {
    Month: "Jul (Q3)",
    DefectRate_DPMO: 42000,
    ScrapRework_Cost_M: 2.5,
    OnTimeDelivery_Pct: 84.0,
    ProcessYield_Pct: 95.8,
  },
  {
    Month: "Aug (Q3)",
    DefectRate_DPMO: 40000,
    ScrapRework_Cost_M: 2.4,
    OnTimeDelivery_Pct: 85.5,
    ProcessYield_Pct: 96.0,
  },
  {
    Month: "Sep (Q3)",
    DefectRate_DPMO: 45000,
    ScrapRework_Cost_M: 2.8,
    OnTimeDelivery_Pct: 82.0,
    ProcessYield_Pct: 95.5,
  },
  {
    Month: "Oct (Q4)",
    DefectRate_DPMO: 48000,
    ScrapRework_Cost_M: 3.0,
    OnTimeDelivery_Pct: 80.5,
    ProcessYield_Pct: 95.2,
  },
  {
    Month: "Nov (Q4)",
    DefectRate_DPMO: 51000,
    ScrapRework_Cost_M: 3.2,
    OnTimeDelivery_Pct: 78.0,
    ProcessYield_Pct: 94.9,
  },
  {
    Month: "Dec (Q4)",
    DefectRate_DPMO: 55000,
    ScrapRework_Cost_M: 3.5,
    OnTimeDelivery_Pct: 75.0,
    ProcessYield_Pct: 94.5,
  },
];
